language: cpp

sudo: false

services:
  - docker

before_install:
  # execute all of the commands which need to be executed 
  # before installing dependencies

install:
  # install all of the dependencies you need here
  - docker run --name setup -v "${TRAVIS_BUILD_DIR}:/build/git" gnuton/vitasdk-docker /bin/bash /build/git/scripts/travis/setup.sh
  - docker logs setup
  - docker commit setup build_img 

before_script:
  # execute all of the commands which need to be executed 
  # before running actual tests

script:
  # execute all of the commands which should make the build pass or fail
  - docker run --name build -v "${TRAVIS_BUILD_DIR}:/build/git" build_img /bin/bash /build/git/scripts/travis/build.sh
  - docker logs build

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "/build/git/app/build/hello_cpp_world.vpk"
  skip_cleanup: true
  on:
    tags: false
