language: cpp

services:
  - docker

before_install:
  - docker run -d -v "${TRAVIS_BUILD_DIR}:/build" gnuton/vitasdk-docker
  - docker ps -a

script:
  - cd /build
  - ls
  - cd app
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make 
